LANGUAGES = [
    ("🇺🇿 Uzbek", "uz"),
    ("🇷🇺 Russian", "ru"),
    ("🇬🇧 English", "en"),
    ("🇫🇷 French", "fr"),
    ("🇩🇪 German", "de"),
    ("🇮🇹 Italian", "it"),
    ("🇪🇸 Spanish", "es"),
    ("🇸🇦 Arabic", "ar"),
    ("🇹🇷 Turkish", "tr"),
    ("🇨🇳 Chinese (Simplified)", "zh-cn"),
    ("🇨🇳 Chinese (Traditional)", "zh-tw"),
    ("🇧🇾 Belarusian", "be"),
    ("🇮🇳 Hindi", "hi"),
    ("🇯🇵 Japanese", "ja"),
    ("🇰🇷 Korean", "ko"),
    ("🇮🇩 Indonesian", "id"),
    ("🇵🇱 Polish", "pl"),
    ("🇵🇹 Portuguese (Portugal)", "por"),
    ("🇧🇷 Portuguese (Brazil)", "pt"),
    ("🇷🇴 Romanian", "ro"),
    ("🇹🇭 Thai", "th"),
    ("🇻🇳 Vietnamese", "vi"),
    ("🇸🇪 Swedish", "sv"),
    ("🇳🇴 Norwegian", "no"),
    ("🇫🇮 Finnish", "fi"),
    ("🇩🇰 Danish", "da"),
    ("🇳🇱 Dutch", "nl"),
    ("🇬🇷 Greek", "el"),
    ("🇮🇪 Irish", "ga"),
    ("🇵🇭 Filipino (Tagalog)", "fil"),
    ("🇪🇪 Estonian", "et"),
    ("🇱🇹 Lithuanian", "lt"),
    ("🇱🇻 Latvian", "lv"),
    ("🇭🇺 Hungarian", "hu"),
    ("🇨🇿 Czech", "cs"),
    ("🇸🇰 Slovak", "sk"),
    ("🇸🇮 Slovenian", "sl"),
    ("🇭🇷 Croatian", "hr"),
    ("🇧🇬 Bulgarian", "bg"),
    ("🇷🇸 Serbian", "sr"),
    ("🇧🇦 Bosnian", "bs"),
    ("🇲🇰 Macedonian", "mk"),
    ("🇦🇱 Albanian", "sq"),
    ("🇦🇷 Armenian", "hy"),
    ("🇬🇪 Georgian", "ka"),
    ("🇲🇳 Mongolian", "mn"),
    ("🇲🇾 Malay", "ms"),
    ("🇲🇻 Dhivehi", "dv"),
    ("🇱🇦 Lao", "lo"),
    ("🇰🇭 Khmer", "km"),
    ("🇮🇱 Hebrew", "he"),
    ("🇸🇩 Sindhi", "sd"),
    ("🇵🇰 Urdu", "ur"),
    ("🇰🇿 Kazakh", "kk"),
    ("🇹🇯 Tajik", "tg"),
    ("🇺🇿 Uzbek", "uz"),
    ("🇰🇬 Kyrgyz", "ky"),
    ("🇹🇲 Turkmen", "tk"),
    ("🇲🇷 Marathi", "mr"),
    ("🇧🇩 Bengali", "bn"),
    ("🇵🇸 Pashto", "ps"),
    ("🇳🇵 Nepali", "ne"),
    ("🇱🇦 Latin", "la")
]

